{McS: 1100, Texp: 4.5, Tins: 3.3, VAZ: 0.35, bFrq: 7.69, c: 1.25, calibrate: false,
  optSet: false, pCrt: 150.0, pres: 9, proc: false, session: !!timestamp '2020-06-30
    11:50:04.225275', start: false}
